name: myenv
channels:
  - conda-forge
  - bioconda
  - nvidia
  - pytorch
  - main
  - r
dependencies:
  - ipykernel=6.29.5
  - pip=25.0
  - python=3.12.8
  - pip:
      - h5py==3.12.1
      - matplotlib==3.10.0
      - numpy==2.2.2
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - pillow==11.1.0
      - pytorch-lightning==2.5.0.post0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - torch==2.6.0
      - torcheval==0.0.7
      - torchmetrics==1.6.1
      - torchsummary==1.5.1
      - torchvision==0.21.0
      - tqdm==4.67.1

